- frontend/.storybook/preview.js
- frontend/package.json
- frontend/src/App.style.ts
- frontend/src/App.tsx
- frontend/src/assets/icons/cancel.svg
- frontend/src/components/@shared/Chip/Chip.stories.tsx
- frontend/src/components/@shared/Chip/Chip.style.ts
- frontend/src/components/@shared/Chip/Chip.tsx
- frontend/src/react-app-env.d.ts
- frontend/webpack.config.ts
- frontend/yarn.lock
Chip컴포넌트 구현
- 전역 스타일 적용
- 스토리북 기본설정
- svg inline loader 설치 및 적용
> Chip 컴포넌트 구현

- frontend/src/assets/images/defaultProfile.svg
- frontend/src/components/@shared/Avatar/Avatar.stories.tsx
- frontend/src/components/@shared/Avatar/Avatar.style.ts
- frontend/src/components/@shared/Avatar/Avatar.tsx
Avatar 컴포넌트 구현
- 프로필 이미지가 없을 경우를 위해 defaultProfile.svg 추가
> Avatar 컴포넌트 구현

- frontend/src/components/@shared/CountIndicator/CountIndicator.stories.tsx
- frontend/src/components/@shared/CountIndicator/CountIndicator.style.ts
- frontend/src/components/@shared/CountIndicator/CountIndicator.tsx
> CountIndicator 컴포넌트 구현

- frontend/src/react-app-env.d.ts
- 자동으로 any 로 추론되는 styled-components 의 theme 객체에 타입을 부여.
- 타입 부여를 위해 react-app-env.d.ts 의 내용 수정
> chore: styled-components 의 theme 객체에 타입을 부여 (#22)

- frontend/package.json
- frontend/src/App.style.ts
- frontend/yarn.lock
> css normalize 적용

- frontend/.storybook/main.js
- frontend/tsconfig.json
- 스토리북 webpack 에 svgr 적용
- tsconfig.json 의 불필요한 공백 제거
> 스토리북 webpack 에 svgr 적용

- frontend/src/assets/icons/add-box.svg
- frontend/src/assets/icons/home.svg
- frontend/src/assets/icons/index.tsx
- frontend/src/assets/icons/login.svg
- frontend/src/assets/icons/person.svg
- frontend/src/assets/icons/search.svg
- svg 파일 추가 및 svg 컴포넌트를 하나의 파일에서 import 해올 수 있도록 설정
> chore: svg 파일 추가 및 svg 컴포넌트를 하나의 파일에서 import 해올 수 있도록 설정

- backend/pick-git/src/main/java/com/woowacourse/pickgit/PickGitApplication.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/AuthService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/domain/OAuth.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/AuthController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/common/JwtXXX.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/AuthConfiguration.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostContents.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Posts.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/comment/Comment.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/comment/CommentContent.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/comment/Comments.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/content/Picture.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/content/Pictures.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/like/Like.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/like/Likes.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/domain/Tag.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/domain/Tags.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/Vendor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/follow/Follow.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/follow/Followers.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/follow/Followings.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/profile/BasicProfile.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/profile/GithubProfile.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/statistics/UserStatistics.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/GithubVendor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/resolver/ResolverAnnotation.java
- 도메인별 상위 패키지 구분 및 세부적으로 웹 계층에 맞는 패키지 구조 정의
- 클래스 필드명 정의
> [chore/package-structure] 패키지 구조 분리 및 스켈레톤 코드 작성

- frontend/src/components/@shared/CircleIcon/CircleIcon.stories.tsx
- frontend/src/components/@shared/CircleIcon/CircleIcon.style.ts
- frontend/src/components/@shared/CircleIcon/CircleIcon.tsx
> CricleIcon 컴포넌트 구현

- frontend/src/@types/assets.d.ts
- frontend/src/App.style.ts
- frontend/src/components/layout/NavigationHeader/NavigationHeader.stories.tsx
- frontend/src/components/layout/NavigationHeader/NavigationHeader.style.ts
- frontend/src/components/layout/NavigationHeader/NavigationHeader.tsx
- frontend/src/constants/path.ts
- NavigationHeader 컴포넌트 구현
- 이미지 파일 모듈에 대한 typing 적용
- a 태그에 전역으로 부여된 hover 텍스트 color 제거
> [#6] NavigationHeader 컴포넌트 구현

- frontend/src/assets/icons/go-back.svg
- frontend/src/assets/icons/go-forward.svg
- frontend/src/assets/icons/index.tsx
- frontend/src/components/layout/StepHeader/StepHeader.stories.tsx
- frontend/src/components/layout/StepHeader/StepHeader.style.ts
- frontend/src/components/layout/StepHeader/StepHeader.tsx
- StepHeader 컴포넌트 구현
- 아이콘 svg 파일 추가
> [#7] StepHeader 컴포넌트 구현

- frontend/src/App.style.ts
- frontend/src/components/@shared/Tabs/Tabs.stories.tsx
- frontend/src/components/@shared/Tabs/Tabs.style.ts
- frontend/src/components/@shared/Tabs/Tabs.tsx
- Tabs 컴포넌트 구현
- 전역 색상 테마로 lighterTextColor 추가
> [#14] Tabs 컴포넌트 구현

- frontend/src/components/@shared/ContributionGraph/ContributionGraph.stories.tsx
- frontend/src/components/@shared/ContributionGraph/ContributionGraph.style.ts
- frontend/src/components/@shared/ContributionGraph/ContributionGraph.tsx
> [#11] ContributionGraph 컴포넌트 구현

- frontend/src/components/@shared/Input/Input.stories.tsx
- frontend/src/components/@shared/Input/Input.style.ts
- frontend/src/components/@shared/Input/Input.tsx
> [#9] Input 컴포넌트 구현

- frontend/src/components/@shared/Button/Button.stories.tsx
- frontend/src/components/@shared/Button/Button.style.ts
- frontend/src/components/@shared/Button/Button.tsx
> [#41] Button 컴포넌트 구현

- frontend/src/assets/icons/heart-line.svg
- frontend/src/assets/icons/heart.svg
- frontend/src/assets/icons/index.tsx
- frontend/src/components/@shared/Comment/Comment.stories.tsx
- frontend/src/components/@shared/Comment/Comment.style.ts
- frontend/src/components/@shared/Comment/Comment.tsx
- Comment 컴포넌트 구현
- 좋아요 기능을 위한 아이콘 2개 추가
> [#63] Comment 컴포넌트 구현

- frontend/src/assets/icons/edit.svg
- frontend/src/assets/icons/github.svg
- frontend/src/assets/icons/index.tsx
- frontend/src/assets/icons/post-heart-line.svg
- frontend/src/assets/icons/post-heart.svg
- frontend/src/components/@shared/Comment/Comment.stories.tsx
- frontend/src/components/@shared/Comment/Comment.style.ts
- frontend/src/components/@shared/Comment/Comment.tsx
- frontend/src/components/@shared/Input/Input.tsx
- frontend/src/components/@shared/PostItem/PostItem.stories.tsx
- frontend/src/components/@shared/PostItem/PostItem.style.ts
- frontend/src/components/@shared/PostItem/PostItem.tsx
- frontend/src/components/@shared/TextEditor/TextEditor.style.ts
- frontend/src/components/@shared/TextEditor/TextEditor.tsx
- Feature 컴포넌트 구현
- svg 파일 추가
- 다른 shared 컴포넌트 수정
> [#5] PostItem 컴포넌트 구현

- backend/pick-git/build.gradle
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/AuthenticationInterceptor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/PickGitAdvice.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/dto/PickGitExceptionResponse.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/PostRequestDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/PostResponseDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostContent.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostRepository.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/content/Image.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/content/Images.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/PostRequest.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/UserRepository.java
- backend/pick-git/src/main/resources/application-test.yml
- backend/pick-git/src/test/java/com/woowacourse/pickgit/PickGitApplicationTests.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/OAuthControllerTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/PostAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostServiceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/domain/PostContentTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/domain/PostRepositoryTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/integration/PostIntegrationTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/presentation/PostControllerTest.java
- AppUser
- LoginUser인 경우 게시물 등록
- GuestUser인 경우 예외 발생
- 테스트
- 도메인 테스트
- 서비스 슬라이스 테스트 + 통합 테스트
- Data JPA 테스트
- 인수 테스트
- 컨트롤러 테스트
- GuestUser인 경우
- 현재는 Controller에서 예외가 발생하는데, @Authenticated 로직 질문하고 Service로 옮길 수 있으면 바꿀 예정임
- `IllegalArgumentException`이 발생하는데, 예외처리 전략 논의하고 커스텀 예외로 변경할 예정임
> [#40] 게시물 작성 기능 구현

- frontend/src/components/@shared/Button/Button.stories.tsx
- frontend/src/components/@shared/Button/Button.style.ts
- frontend/src/components/@shared/Button/Button.tsx
- SquaredBlock추가
- RoundedInline추가
> [#107] Button 컴포넌트 kind type 추가

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
- backend/pick-git/src/main/resources/application-test.yml
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostServiceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/domain/PostRepositoryTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/domain/PostTest.java
- Post에 Github Repository url 관련 칼럼을 추가한다.
- 스켈레톤에서 누락된 칼럼을 추가한 것이다.
> [#102] 게시물에 Github Repository 주소 추가 기능 구현 

- .gitmodules
- backend/pick-git/.gitignore
- backend/pick-git/build.gradle
- backend/pick-git/src/main/resources/application.yml
- application security 데이터를 서브모듈에서 관리하도록 설정함
> [#119] 서브모듈 적용

- backend/pick-git/script/deploy_script.sh
- frontend/script/deploy_script.sh
- jenkinsfiles/backend-dev
- jenkinsfiles/backend-prod
- jenkinsfiles/frontend-dev
- jenkinsfiles/frontend-prod
- jenkinsfiles/s3proxy
- s3-proxy/s3-proxy/script/deploy_script.sh
jenkins를 실행하기 위한 설정파일.
pipeline기반의 스크립트 사용.
> [#127] 젠킨스 설정 파일 생성

- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/AuthenticationInterceptor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/PostAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/presentation/PostControllerTest.java
* 비로그인 유저로 홈 피드 조회가 안 되는 문제 인터셉터 개선
* 비로그인 유저의 홈 피드 조회 테스트 추가
> [#134] 비로그인 유저로도 홈 피드 조회

- frontend/src/App.tsx
- frontend/src/components/Profile/Profile.tsx
- frontend/src/components/ProfileFeed/ProfileFeed.tsx
- frontend/src/constants/urls.ts
- frontend/src/pages/ProfilePage/ProfilePage.stories.tsx
- frontend/src/pages/ProfilePage/ProfilePage.tsx
- frontend/src/services/queries/posts.ts
- frontend/src/services/queries/profile.ts
- route된 페이지에서 새로고침이 안되는건 내 착각이었음 ㅠ
- 다만 params(예를들어 /user/:userName) 를 사용해 route하는 경우 브라우저가 해당 url을 루트로 하는 번들 파일(/user/bundle.js)을 찾으려고해 새로고침 할 수 없는 문제가 발생
- params에 대해 새로고침 이슈를 해결할 수 있는 방법은 찾지 못했으나 우선 params를 사용하지 않도록 수정
> [#127] reload 이슈 해결

- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/OAuthController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/IgnoreAuthenticationInterceptor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/presentation/TagController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserController.java
- 각 Controller에 CORS 옵션 설정
- security redirect URL 변경
> [hotfix] CORS 버그 해결

- backend/pick-git/script/deploy_script.sh
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/PostAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostFactory.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostServiceIntegrationTest.java
- s3-proxy/s3-proxy/script/deploy_script.sh
* 페이징을 통해 내 프로필 계정의 게시물 조회 가능
* 날짜 최신순으로 조회해서 보냄
* 비로그인일때는 접근 불가 (/api/posts/me)
* 관련 인수 테스트 및 서비스 통합 테스트 작성
* 현재 jpql이 서비스에 산재하고 있어서 해당 부분 리팩토링이 필요함
> [#137] 내 프로필 계정의 게시물을 조회한다.

- frontend/src/App.tsx
- frontend/src/components/@layout/NavigationHeader/NavigationHeader.stories.tsx
- frontend/src/components/@layout/NavigationHeader/NavigationHeader.tsx
- frontend/src/constants/urls.ts
- frontend/src/services/requests/index.ts
- frontend/src/services/requests/posts.ts
- frontend/webpack.config.ts
- login mock 제거
- post조회 시page, limit mock
- 배포 모드에 따라 proxy를 적용하도록 수정
> [chore] api mocking 관련 코드 수정

- backend/pick-git/.gitignore
- backend/pick-git/build.gradle
* .gitignore에 prod yml 제외
* 클래스패스로 prod yml 복사
* security 저장소에 mariadb 환경 prod.yml 설정파일 업로드
> [#143] 운영 환경 설정을 위한 서브 모듈 세팅

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostDtoAssembler.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostRepository.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/HomeFeedRequest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/PostAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostServiceIntegrationTest.java
- 로그인 유저인 경우 해당 유저의 Posts들에 대한 좋아요 여부값을 `true`/`false`로 반환한다. 
- 게스트 유저인 경우 해당 유저의 Posts들에 대한 좋아요 여부값을 `null`로 반환한다.
> [#141] 다른 유저의 프로필 계정의 게시물 조회 

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostRepository.java
> [hotfix] PostRepository에 @Param 추가 

- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/OAuthController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/dto/OAuthTokenResponse.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/AuthenticationInterceptor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/IgnoreAuthenticationInterceptor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/PathMatchInterceptor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/OAuthControllerTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/tag/presentation/TagControllerTest.java
- 프론트와 협의한 결과 로그인 결과에 username 포함하도록 수정
- 인터셉터 Matcher Http Method도 같이 매치되도록 리팩토링
> 급하게 구현하느라 Matcher쪽에 메서드 분리 못시킨 부분이 있는데 추후에 리팩토링 할게요 :)
> [#146] 로그인 반환 값에 유저 네임 추가 및 인터셉터 매치 기능 리팩토링

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/S3Storage.java
> [hotfix] s3-storage 응답 파싱 에러 수정

- frontend/public/index.html
- frontend/src/App.style.ts
- frontend/src/components/@shared/ProfileHeader/ProfileHeader.tsx
- frontend/src/components/Feed/Feed.tsx
- frontend/src/contexts/UserContext.tsx
- frontend/src/services/hooks/@common/useLocalStorage.ts
- frontend/src/services/queries/profile.ts
- frontend/src/services/requests/profile.ts
- 어플리케이션 진입시 로그인 상태를 확인하는 로직 추가
- 우선 token이 있으면 로그인 상태로 간주하고 홈피드 조회시 서버에서 401을 던져주면 로그아웃하는 방식으로 구현
- 추후 유효한 유저인지 확인하는 api를 추가하는 것이 좋을 것 같음
> [#129] follow 추가, 취소 기능 구현

- jenkinsfiles/backend-dev
- jenkinsfiles/backend-prod
- jenkinsfiles/frontend-dev
- jenkinsfiles/frontend-prod
- jenkinsfiles/s3proxy
기존의 빌드 유발 방식은 pull request merge시 전체 worker들에게 전파, 그 후 스크립트에서 자신의 담당 부분을 검증하고 변경이 일어났다면 빌드를 진행했다.
변경 후, label을 기반으로 빌드 유발을 하기 때문에 검증 로직이 삭제된다.
> [#156] 젠킨슨 설정 파일 변경

- s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/S3ProxyAcceptanceTest.java
- s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/common/FileFactory.java
- s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/common/fileValidator/ImageFileValidatorTest.java
- s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/config/StorageTestConfiguration.java
- s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/web/infrastructure/FileNameGeneratorTest.java
- s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/web/infrastructure/S3StorageIntegrationTest.java
- s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/web/presentation/PickGitStorageControllerTest.java
#164 와 관련, test코드쪽의 unimport 누락.
> [#163] 빌드 에러를 확인.

- frontend/src/components/ProfileFeed/ProfileFeed.styled.ts
- frontend/src/components/ProfileFeed/ProfileFeed.tsx
- frontend/src/constants/urls.ts
- frontend/src/contexts/UserContext.tsx
- frontend/src/pages/ProfilePage/ProfilePage.tsx
- UserContext에서 /profile/me api에 요청을 보내 토큰 유효성확인
- 자기 이름을 query string에 넣고 프로필페이지에 들어왔을때 profile/me로 리디렉트
- 프로필 페이지에서 빈 게시물 표시
> [fix] 프론트엔드 이슈 수정

- frontend/src/components/@shared/PostItem/PostItem.tsx
- frontend/src/constants/urls.ts
- frontend/src/contexts/UserContext.tsx
- url 오타수정
- 게시물 태그 문자열 파싱 오류 해결
- 불필요한 의존성 제거
> [fix] 프론트엔드 버그 수정

- frontend/src/components/@shared/InfiniteScrollContainer/InfiniteScrollContainer.stories.tsx
- frontend/src/components/@shared/InfiniteScrollContainer/InfiniteScrollContainer.style.ts
- frontend/src/components/@shared/InfiniteScrollContainer/InfiniteScrollContainer.tsx
- frontend/src/components/@shared/Loader/Loader.stories.tsx
- frontend/src/components/@shared/Loader/Loader.style.ts
- frontend/src/components/@shared/Loader/Loader.tsx
- InfiniteScrollContainer & Loader 컴포넌트를 구현
> [#173] Feature/loader and infinite scroll container

- frontend/src/App.tsx
- frontend/src/components/@shared/InfiniteScrollContainer/InfiniteScrollContainer.style.ts
- frontend/src/components/Feed/Feed.stories.tsx
- frontend/src/components/Feed/Feed.tsx
- frontend/src/constants/urls.ts
- frontend/src/pages/AddPostPage/AddPostPage.stories.tsx
- frontend/src/pages/AddPostPage/AddPostPage.tsx
- frontend/src/pages/HomeFeedPage/HomeFeedPage.tsx
- frontend/src/pages/TagFeedPage/TagFeedPage.stories.tsx
- frontend/src/pages/TagFeedPage/TagFeedPage.style.ts
- frontend/src/pages/TagFeedPage/TagFeedPage.tsx
- frontend/src/pages/UserFeedPage/UserFeedPage.stories.tsx
- frontend/src/pages/UserFeedPage/UserFeedPage.style.ts
- frontend/src/pages/UserFeedPage/UserFeedPage.tsx
- frontend/src/services/hooks/useFeed.ts
- frontend/src/services/hooks/usePostUpload.ts
- frontend/src/services/queries/posts.ts
- frontend/src/services/requests/posts.ts
- Infinite Scroll 기능 구현
- 페이지 컴포넌트에서 데이터를 fetch 받도록 수정
- TagFeedPage & UserFeed 페이지 추가
- 기능 구현 X
- PAGE_URL 상수 추가
- 기존의 평문으로 제공되던 userName 을 로그인 된 유저 이름이 제공되도록 변경
> [#128] Infinite Scroll 기능 구현

- frontend/src/components/TagInputForm/TagInputForm.tsx
- frontend/src/services/queries/github.ts
- frontend/src/services/requests/github.ts
- userName 이 파라미터로 들어가지 않은 문제 해결
> [#185] userName 과 repositoryName 이 없을 때 데이터가 fetch 되는 버그를 해결

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostRepository.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostServiceIntegrationTest.java
> [#189] 홈 피드 조회 기능을 최신순으로 변경

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/dto/RepositoryResponseDto.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostServiceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/presentation/PostControllerTest.java
- 퍼블릭 레포지토리 이름뿐만 아니라 URL도 함께 응답하도록 수정했습니다.
> [#179] Github Repositories 조회 기능 수정

- frontend/src/App.style.ts
- frontend/src/App.tsx
- frontend/src/components/@layout/PageLoading/PageLoading.stories.tsx
- frontend/src/components/@layout/PageLoading/PageLoading.style.ts
- frontend/src/components/@layout/PageLoading/PageLoading.tsx
- frontend/src/components/@shared/InfiniteScrollContainer/InfiniteScrollContainer.tsx
- frontend/src/components/@shared/PostItem/PostItem.style.ts
- frontend/src/components/@styled/layout.tsx
- frontend/src/components/Feed/Feed.stories.tsx
- frontend/src/components/Feed/Feed.style.ts
- frontend/src/components/Feed/Feed.tsx
- frontend/src/components/Profile/Profile.tsx
- frontend/src/components/RepositorySelector/RepositorySelector.style.tsx
- frontend/src/components/RepositorySelector/RepositorySelector.tsx
- frontend/src/components/TagInputForm/TagInputForm.tsx
- frontend/src/pages/AddPostPage/AddPostPage.style.ts
- frontend/src/pages/AuthLoginProcessingPage/AuthLoginProcessingPage.style.ts
- frontend/src/pages/HomeFeedPage/HomeFeedPage.tsx
- frontend/src/pages/LoginPage/LoginPage.style.ts
- frontend/src/pages/ProfilePage/ProfilePage.style.ts
- frontend/src/pages/TagFeedPage/TagFeedPage.tsx
- frontend/src/pages/UserFeedPage/UserFeedPage.tsx
- 게시글 추가 페이지에서 레포지터리 개수에 따라 페이지 높이가 늘어나는 문제 해결
- 데이터 요청 시 Loader 컴포넌트를 요청 중에 보여주기
- Infinite Scroll 로 가져올 추가적인 데이터가 없을 시 Loader 를 숨기기
- 깃허브 로그인 시 로딩 창의 높이를 이용자의 기기나 브라우저 높이에 맞도록 자동으로 조정
- 모바일 반응형 break point 재설정 &  각 페이지 컴포넌트의 Container 에 Page 스타일드 컴포넌트 확장 적용
- PostItem 컴포넌트 헤더 부분 padding 값 수정
> [#197] 레이아웃 및 UI를 개선

- frontend/src/components/@layout/NavigationHeader/NavigationHeader.stories.tsx
- frontend/src/components/@layout/NavigationHeader/NavigationHeader.style.ts
- frontend/src/components/@layout/NavigationHeader/NavigationHeader.tsx
> [#197] 로그아웃 기능 구현

- backend/pick-git/build.gradle
- backend/pick-git/gradle/wrapper/gradle-wrapper.properties
- backend/pick-git/src/docs/asciidoc/authorization.adoc
- backend/pick-git/src/docs/asciidoc/comment.adoc
- backend/pick-git/src/docs/asciidoc/following.adoc
- backend/pick-git/src/docs/asciidoc/index.adoc
- backend/pick-git/src/docs/asciidoc/post.adoc
- backend/pick-git/src/docs/asciidoc/profile.adoc
- backend/pick-git/src/docs/asciidoc/tag.adoc
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
- backend/pick-git/src/main/resources/static/docs/index.html
- backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/OAuthControllerTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/docs/ApiDocumentUtils.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/application/PostFactory.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/post/presentation/PostControllerTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/tag/presentation/TagControllerTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/user/UserFactory.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/user/presentation/UserControllerTest.java
bootJar에서 static 파일 copy가 바로 이루어 지지 않아서 copy를 하는 task를 따로 두고 bootjar에 dependsOn으로 의존성을 주었음.
gradle 7.x에서는 asciidoctor에 문제가 있어 6.8.3으로 다운그레이드 하였음.
mvc 테스트를 더 견고하게 작성해야할 필요성을 느낌.
> [#194] REST Docs 적용

- backend/pick-git/script/deploy_script.sh
- jenkinsfiles/backend-dev
- jenkinsfiles/backend-prod
- jenkinsfiles/frontend-prod
- jenkinsfiles/s3proxy
- s3-proxy/s3-proxy/script/deploy_script.sh
> [#207] 배포 자동화 버그 수정

- frontend/package.json
- frontend/src/services/requests/index.ts
- frontend/webpack.config.ts
- main:  api.pickgit.....
- develop: devapi.pickgit...
- webpack-dev-server(로컬): devapi.pickgit... 에 proxy로 요청
> [#212] 배포 환경에 따라 api url 분기

- jenkinsfiles/frontend-dev
> [#212] 프론트엔드 빌드 커맨드 수정

- frontend/src/components/@styled/layout.tsx
- frontend/src/components/TagInputForm/TagInputForm.tsx
- frontend/src/services/queries/github.ts
- 게시글 추가 시, 초기에 불러온 기본 tag 들이 사라지지 않는 문제를 해결
- 게시글 추가 중 태그 삭제 기능 구현
- break point 에 맞게 어플리케이션 최대 너비를 375px -> 425px 로 조정
> [#200, #205] 태그 관련 이슈 해결

- frontend/src/components/@layout/NavigationHeader/NavigationHeader.tsx
- frontend/src/components/@shared/ImageSlider/ImageSlider.style.ts
- frontend/src/components/@shared/ImageSlider/ImageSlider.tsx
- frontend/src/components/@styled/layout.tsx
- frontend/src/constants/layout.ts
- 비로그인 시에도 홈 네이게이션이 나오도록 수정
- 이미지 슬라이더에 인디케이터 추가
<br/>
Close #220 
Close #226
> [#220, #226] 네비게이션 ui 수정 및 이미지 인디케이터 추가

- frontend/src/@types/index.ts
- frontend/src/App.tsx
- frontend/src/components/@shared/PostItem/PostItem.tsx
- frontend/src/components/GithubStatistics/GithubStatistics.tsx
- frontend/src/components/ProfileModificationForm/ProfileModificationForm.tsx
- frontend/src/constants/messages.ts
- frontend/src/constants/urls.ts
- frontend/src/contexts/UserContext.tsx
- frontend/src/pages/ProfilePage/ProfilePage.tsx
- frontend/src/pages/SearchPage/SearchPage.style.ts
- frontend/src/pages/SearchPage/SearchPage.tsx
- frontend/src/services/hooks/useSearchData.ts
- frontend/src/services/queries/githubStats.ts
- frontend/src/services/queries/profile.ts
- frontend/src/services/requests/githubStats.ts
- frontend/src/services/requests/profile.ts
- frontend/src/services/requests/search.ts
- 프로필 수정 요청 메서드를 post로 변경
- 프로필 수정 시 변경된 사진이 없으면 빈 file객체를 전송
- 프로필 수정 시 한 줄 소개는 변경 여부와 관계없이 전송
- 검색 api url 변경
- github stats 요소변경
- contributes => repos
- github-stats api url 변경
- 게시물 ahthor 태그를 통해 본인 프로필 페이지 접근시 profile/me 페이지로 매핑
<br/>
Close #262 
Close #275
Close #276
> [#124, #262, #275, #276] 요청 관련 이슈 해결

- backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
- 게시물 수정 및 삭제 로직 변경에 따른 테스트 실패 버그를 해결했습니다.
<br/>
Close #284
> [#284] 게시물 수정 및 삭제 버그 해결

- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/PlatformContributionExtractor.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/calculator/GithubContributionCalculator.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/dto/ItemDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/extractor/GithubContributionExtractor.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockContributionApiRequester.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/infrastructure/GithubContributionCalculatorTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/infrastructure/GithubContributionExtractorTest.java
- Github API 응답 형식에 맞게 DTO를 변경했습니다.
<br/>
Close #287
> [#287] Github 통계 조회 버그 해결

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/CommentResponse.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/response/LikeResponseDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/response/PostResponseDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/response/CommentResponse.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/response/LikeResponse.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/common/factory/PostFactory.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostControllerTest.java
- like 관련 DTO 필드명을 변경
- `likesCount` -> `likeCount`
- `isLiked` -> `liked` 
<br/>
Close #289
> [#289] like 관련 DTO 필드명 변경

- backend/pick-git/src/main/resources/logback-access.xml
- backend/pick-git/src/main/resources/logback-spring.xml
- backend/pick-git/src/main/resources/static/docs/index.html
- s3-proxy/s3-proxy/src/main/resources/logback-access.xml
- s3-proxy/s3-proxy/src/main/resources/logback-spring.xml
* ubuntu 환경에서 경로에서 ./ 부분 삭제하니 정상 작동합니다. (.만 빼도 되긴하는데 찜찜해서 슬래시까지 전부 삭제)
<br/>
* 이전 유저 리팩토링하면서 테스트 변경으로 인해 rest docs도 변경이 있었는데 깜빡해서 추가합니다.
<br/>
Close #293
> [#293]  Logback 인식 불가 버그 해결

- frontend/src/components/ProfileModificationForm/ProfileModificationForm.tsx
- frontend/src/components/SearchListUser/SearchListUser.style.ts
- frontend/src/components/SearchListUser/SearchListUser.tsx
- frontend/src/constants/messages.ts
- frontend/src/services/hooks/useProfileModificationForm.ts
- frontend/src/services/queries/profile.ts
- frontend/src/services/requests/index.ts
- frontend/webpack.config.ts
- 프로필 페이지 에러처리 수준 수정
- 프로필 페이지 서비스 로직 분리
- 프로필 수정 후 반영되지 않는 버그 수정
- 검색 리스트에 프로필 페이지 링크 추가
Close #273 
Close #301
> [#273, #301] profile page 에러처리 수준 수정 및 기타 버그 해결

- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
- 아래 부분 설정을 수정함.
- /api/posts
- /api/posts/{username}
- 테스트 코드 조금 수정.
<br/>
Close #296
> [#296] 게시물 조회 인증 관련된 설정문제 해결

- frontend/src/services/requests/index.ts
- frontend/webpack.config.ts
> [#304] api url 수정

- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Posts.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/comment/Comments.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/content/Images.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
- Post - Comments 영속성 전이 버그를 해결했습니다.
- 사용자가 댓글이 있는 게시물을 삭제하는 테스트도 추가했습니다.
<br/>
Close #306
> [#306] 게시물 삭제 버그 해결

- frontend/src/@types/index.ts
- frontend/src/components/CommentSlider/CommentSlider.tsx
- frontend/src/components/GithubStatistics/GithubStatistics.tsx
- frontend/src/pages/ProfilePage/ProfilePage.style.ts
- frontend/src/services/requests/githubStats.ts
- frontend/src/services/requests/index.ts
- 프로필 페이지 하단 레이아웃 오버플로우
- 깃헙 통계 임시 api로 수정
- api url 오타 수정
<br/>
Close #310
> [#310] 팀데모 결과 반영 - 프로필 페이지

- frontend/src/components/@shared/ImageSlider/ImageSlider.style.ts
- frontend/src/components/@shared/PostItem/PostItem.tsx
- frontend/src/components/@shared/TextEditor/TextEditor.style.ts
- frontend/src/components/Feed/Feed.tsx
- frontend/src/components/SearchListUser/SearchListUser.tsx
- frontend/src/constants/messages.ts
- 검색 리스트에서 팔로우시 깜박거리는 이슈해결
- 게시물 삭제시 컨펌 모달 노출
- 게시물 더보기 하면 '간략히'버튼 노출
- 이미지, 텍스트 인디케이터 사이즈 고정<br/>
Close #316
> [#316] 3차데모 검색 페이지 및 UI 관련 이슈 해결

- frontend/src/components/@shared/PostItem/PostItem.tsx
- frontend/src/constants/messages.ts
- frontend/src/pages/AddPostPage/AddPostPage.tsx
> [#320] 게시물 추가 시 이미지가 없으면 alert처리

- frontend/src/components/@layout/SearchHeader/SearchHeader.tsx
- frontend/src/components/@shared/PostItem/PostItem.style.ts
- frontend/src/components/@shared/PostItem/PostItem.tsx
- frontend/src/components/@shared/Tabs/Tabs.tsx
- frontend/src/constants/urls.ts
- frontend/src/pages/SearchPage/SearchPage.tsx
- frontend/src/services/hooks/useSearchPostData.ts
- 태그 클릭 시 검색 페이지로 이동
- 해당 태그를 검색어로 추가
- 태그 검색 탭으로 이동
<br/>
Close #349
> [#349] 태그 클릭 시 검색 페이지로 이동

- frontend/src/components/@shared/ProfileHeader/ProfileHeader.tsx
- frontend/src/components/SearchListUser/SearchListUser.tsx
- frontend/src/constants/messages.ts
- frontend/src/constants/urls.ts
- frontend/src/services/hooks/@tests/useFollow.test.tsx
- frontend/src/services/hooks/useFollow.ts
- frontend/src/services/queries/profile.ts
- frontend/src/services/requests/profile.ts
- 팔로우/언팔로우 시 깃헙 연동 여부 추가
- 팔로우/ 언팔로우시 confirm 메시지 노출
<br/>
Close #351
> [#351] 팔로우/언팔로우 시 깃헙 연동 여부 추가

- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostFeedControllerTest_searchPosts.java
> [#364]  스니펫 생성 경로 변경

- frontend/src/@types/index.ts
- frontend/src/components/@layout/MessageModalPortal/MessageModalPortal.tsx
- frontend/src/components/@shared/ProfileHeader/ProfileHeader.tsx
- frontend/src/components/GithubStatistics/GithubStatistics.tsx
- frontend/src/components/UserList/UserList.tsx
- frontend/src/pages/FollowingUserListPage/FollowingList.style.ts
- frontend/src/pages/ProfilePage/ProfilePage.style.ts
- frontend/src/pages/SearchPage/SearchPage.style.ts
- frontend/src/services/hooks/useSearchPostData.ts
- 팔로우 목록 페이지 padding 조정
- 프로필 페이지, 검색 페이지 overflow 조정
- 태그 검색 페이지네이션 버그 수정
- 깃헙 통계 contribution => repos로 수정
- 깃헙 팔로우 컨펌 예/아니오로 수정
- UserList 깃헙 팔로우시 컨펌이 닫히지 않는 버그 수정
<br/>
Close #368
> [#368] 팀 1차 데모 버그 수정

- frontend/src/constants/error.ts
- frontend/src/constants/messages.ts
- frontend/src/constants/urls.ts
- frontend/src/services/hooks/useProfileModificationForm.ts
- frontend/src/services/queries/profile.ts
- frontend/src/services/requests/profile.ts
- frontend/src/utils/error.ts
- 프로필 수정 요청 api를 이미지 수정과 한 줄 소개 수정으로 분리
<br/>
Close #367
> [#367] 프로필 수정 api 분리

- backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/GithubOAuthClient.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/UserService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/request/AuthUserForUserRequestDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/request/AuthUserRequestDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/request/FollowRequestDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/follow/PlatformFollowingRequester.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/requester/GithubFollowingRequester.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserController.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserSearchController.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptance_GetFollowingsAndFollowers.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockPlatformFollowingRequester.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/config/InfrastructureTestConfiguration.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/user/UserServiceIntegrationTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/application/UserServiceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/presentation/UserControllerTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/presentation/UserSearchControllerTest.java
- 깃-들다 앱에서 팔로우/언팔로우시 깃헙에도 자동으로 팔로우/언팔로우되는 기능을 구현한다.
<br/>
<br/>
Close #375
> [#375] 팔로우/언팔로우 깃헙 자동 연동 기능구현

- frontend/src/constants/urls.ts
- frontend/src/services/hooks/useProfileModificationForm.ts
- frontend/src/services/requests/profile.ts
- 이미지가 업로드 되지 않는 버그
- 프로필 수정 후에 모달이 닫히지 않는 버그
<br/>
Close #424
> [#424] 팀 2차데모에서 발견한 버그 수정

- backend/pick-git/build.gradle
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/util/dto/SearchRepositoryNameAndUrl.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/dto/RepositoryItemDto.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/extractor/GithubRepositorySearchExtractor.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockRepositoryApiRequester.java
- 중첩 JSON에 대한 파싱 버그를 수정한다. 
<br/>
Close #425
> [#425] 레포 검색 시 JSON 파싱 버그를 수정한다. 

- README.md
- README가 허전해서 작성했습니다.
- 우선 프로젝트, 팀원, 팀 문화를 소개했어요. 나중에 기술 스택 등 추가하면 좋을 거 같습니다!
<br/>
Close #94
> [#94] README 작성

- .github/workflows/FRONTEND_PR_TEST.yml
- 프론트엔드 테스트 자동화 깃헙 액션을 추가한다.
- pr 시 테스트 실행
- 테스트 성공 시 메시지 comment
- 테스트 실패 시 메시지와 함께 chages request
<br/>
Close #442
> [#442] 프론트엔드 테스트 자동화 깃헙 액션 추가

- backend/pick-git/src/main/java/com/woowacourse/pickgit/comment/presentation/CommentController.java
- CommentController에 CORS 설정을 추가했습니다.
<br/>
Close #447
> fix: CORS 버그 해결 (#447)

- .github/workflows/FRONTEND_PR_TEST.yml
- 테스트 성공시 approve하도록 수정
<br/>
Close #455
> [#455] 프론트엔드 테스트 액션 코드 수정

- frontend/src/components/@layout/NavigationHeader/NavigationHeader.style.ts
- frontend/src/components/@layout/NavigationHeader/NavigationHeader.tsx
- frontend/src/components/@layout/SearchHeader/SearchHeader.style.ts
- frontend/src/components/@layout/SearchHeader/SearchHeader.tsx
- frontend/src/components/@layout/StepHeader/StepHeader.style.ts
- frontend/src/components/@layout/StepHeader/StepHeader.tsx
- frontend/src/components/@shared/ImageUploader/ImageUploader.style.ts
- frontend/src/components/@shared/ProfileHeader/ProfileHeader.style.ts
- frontend/src/components/@shared/ProfileHeader/ProfileHeader.tsx
- frontend/src/components/@styled/layout.tsx
- frontend/src/components/@styled/mediaQueries.ts
- frontend/src/components/GithubStatistics/GithubStatistics.style.ts
- frontend/src/components/GithubStatistics/GithubStatistics.tsx
- frontend/src/components/PostContentUploader/PostContentUploader.style.tsx
- frontend/src/components/RepositorySelector/RepositorySelector.style.tsx
- frontend/src/constants/layout.ts
- frontend/src/pages/AddPostPage/AddPostPage.style.ts
- frontend/src/pages/CommentsPage/CommentsPage.style.tsx
- frontend/src/pages/CommentsPage/CommentsPage.tsx
- frontend/src/pages/FollowerList/FollowerList.style.ts
- frontend/src/pages/FollowerList/FollowerList.tsx
- frontend/src/pages/FollowingUserListPage/FollowingList.style.ts
- frontend/src/pages/FollowingUserListPage/FollowingList.tsx
- frontend/src/pages/LoginPage/LoginPage.style.ts
- frontend/src/pages/PostLikePeoplePage/PostLikePeoplePage.style.ts
- frontend/src/pages/PostLikePeoplePage/PostLikePeoplePage.tsx
- frontend/src/services/hooks/useComments.ts
- 반응형 디자인 구현 사항 업데이트
- comment 추가 / 삭제가 화면 상에 바로 반영되도록 수정
<br/>
Close #457
> [#457] 네번째 데모에서 발견된 버그를 해결한다.

- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/AcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/authentication/OAuthAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/comment/CommentAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/comment/CommentAcceptanceTest_delete.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/comment/CommentAcceptanceTest_queryComments.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest_LikeUsers.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest_searchPost.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostRepositorySearchAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/tag/TagAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptanceTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptance_GetFollowingsAndFollowers.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/config/DatabaseCleaner.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostFeedServiceIntegrationTest_search.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest_likeUsers.java
일단은 DirtiesContext만 제거, 추가적으로 속도를 증가시킬 수 있는 방법 구상중.
<br/>
<br/>
Close #436
> [#436] 테스트 코드의 속도를 증진시킨다.

- backend/pick-git/.gitignore
- backend/pick-git/build.gradle
- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/database/DataSourceConfiguration.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/database/MasterDataSourceProperties.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/database/ReplicationRoutingDataSource.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/config/database/SlaveNames.java
- backend/pick-git/src/main/resources/application.yml
- Master DB 1개(CUD) / Slave DB 2개(R)로 분리했습니다.
- application-prod -> application-dev로 변경하고, application-db와 application-prod를 새로 추가했습니다.
- 데이터 마이그레이션도 DB Dump를 이용해서 완료했습니다.
<br/>
Close #474
> [#474] DB Replication 구성

- backend/pick-git/build.gradle
- backend/pick-git/src/docs/asciidoc/comment.adoc
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/comment/presentation/CommentControllerTest_queryComments.java
- Comment AsciiDoc에 빠진 내용을 추가했습니다.
- DB Replication 관련 파일을 제외했습니다.
- 테스트 커버리지 설정을 변경했습니다. (METHOD 단위 -> CLASS 단위 체크, 65% -> 75% 체크)
<br/>
Close #477
> [#477] JaCoCo 수정

- backend/pick-git/build.gradle
pull request sonarcube 파이프라인 구성
* test (./gradlew clean test)
* jacocoreport (./gradlew jacocoreport)
* build (./gradlew build -x test)
* sonarcube
merge 파이프라인 구성
* test (./gradlew clean test)
* restdocs (./gradlew asciidoctor)
* build (./gradlew build -x test)
* deploy
**merge 파이프라인의 경우, 이미 소나큐브에서 자코코 커버리지 충족했다고 판단하고 jacocotestreport 실행 제외**
**소나큐브 파이프라인의 경우, 레스트독스 생성과 관련한 책임이 없다고 생각하여 제외**
---> 이에 대해 자유롭게 의견 부탁드립니다.
<br/>
<br/>
Close #476
> [#476] Gradle Groovy Task 리팩토링 및 파이프라인 개선

- frontend/src/services/requests/index.ts
- frontend/webpack.config.ts
- prod: https://api.pick-git.com/
- dev: https://devapi.pick-git.com:8080/
- local: http://localhost:8080/
Close #484
> [#484] api url 맵핑 수정

- frontend/src/services/requests/index.ts
- frontend/webpack.config.ts
- webpack dev server에 proxy 추가
Close #486
> [#486] local server 운영시 cors 문제가 생기는 이슈 해결

- frontend/src/@types/index.ts
- frontend/src/@types/react-app-env.d.ts
- frontend/src/assets/icons/add-circle-large.svg
- frontend/src/assets/icons/add-circle.svg
- frontend/src/assets/icons/arrow-down.svg
- frontend/src/assets/icons/delete-circle.svg
- frontend/src/assets/icons/index.tsx
- frontend/src/components/@layout/ScrollActiveHeader/ScrollActiveHeader.stories.tsx
- frontend/src/components/@layout/ScrollActiveHeader/ScrollActiveHeader.style.ts
- frontend/src/components/@layout/ScrollActiveHeader/ScrollActiveHeader.tsx
- frontend/src/components/@shared/DateInput/DateInput.stories.tsx
- frontend/src/components/@shared/DateInput/DateInput.style.ts
- frontend/src/components/@shared/DateInput/DateInput.tsx
- frontend/src/components/@shared/DotPaginator/DotPaginator.stories.tsx
- frontend/src/components/@shared/DotPaginator/DotPaginator.style.ts
- frontend/src/components/@shared/DotPaginator/DotPaginator.tsx
- frontend/src/components/@shared/DropDown/DropDown.stories.tsx
- frontend/src/components/@shared/DropDown/DropDown.style.ts
- frontend/src/components/@shared/DropDown/DropDown.tsx
- frontend/src/components/@shared/SVGIcon/SVGIcon.tsx
- frontend/src/components/@shared/ToggleButton/ToggleButton.stories.tsx
- frontend/src/components/@shared/ToggleButton/ToggleButton.style.ts
- frontend/src/components/@shared/ToggleButton/ToggleButton.tsx
- frontend/src/components/@styled/layout.tsx
- frontend/src/components/@styled/mediaQueries.ts
- frontend/src/components/@styled/scrollbar.ts
- frontend/src/components/PostSelector/PostSelector.stories.tsx
- frontend/src/components/PostSelector/PostSelector.style.ts
- frontend/src/components/PostSelector/PostSelector.tsx
- frontend/src/constants/layout.ts
- 아이콘 파일 추가
- SVGIcon 컴포넌트를 통해 각각의 Icon 을 import 하지 않아도 icon 컴포넌트를 사용할 수 있도록 설정
- DropDown 컴포넌트 구현
- DateInput 컴포넌트 구현
- DotPaginator 컴포넌트 구현
- ToggleButton 컴포넌트 구현
- ScrollActiveHeader 컴포넌트 구현
- 커스텀 스크롤바 CSS 구현
- MediaQuery CSS 문 작성을 위한 편의 기능 추가
Close #490
> [#490] 포트폴리오 기능을 위해 필요한 공용 컴포넌트들을 구현

- frontend/src/components/@shared/Avatar/Avatar.style.ts
- frontend/src/components/@shared/Avatar/Avatar.tsx
- frontend/src/components/@shared/Button/Button.style.ts
- frontend/src/components/@shared/Button/Button.tsx
- frontend/src/components/@shared/Chip/Chip.style.ts
- frontend/src/components/@shared/Chip/Chip.tsx
- frontend/src/components/@shared/TextEditor/TextEditor.stories.tsx
- frontend/src/components/@shared/TextEditor/TextEditor.style.ts
- frontend/src/components/@shared/TextEditor/TextEditor.tsx
- frontend/src/components/PortfolioTextEditor/PortfolioTextEditor.stories.tsx
- frontend/src/components/PortfolioTextEditor/PortfolioTextEditor.style.ts
- frontend/src/components/PortfolioTextEditor/PortfolioTextEditor.tsx
- frontend/src/components/PostContentUploader/PostContentUploader.style.tsx
- frontend/src/components/PostContentUploader/PostContentUploader.tsx
- frontend/src/components/PostTextEditor/PostTextEditor.stories.tsx
- frontend/src/components/PostTextEditor/PostTextEditor.style.ts
- frontend/src/components/PostTextEditor/PostTextEditor.tsx
- frontend/src/components/Profile/Profile.style.tsx
- frontend/src/components/ProfileModificationForm/ProfileModificationForm.style.ts
- frontend/src/components/ProfileModificationForm/ProfileModificationForm.tsx
- TextEditor 의 높이 자동 조절 기능 구현 & TextEditor 컴포넌트를 바탕으로하는 PortfolioTextEditor, PostTextEditor 생
성 및 적용
- feat: 기존 컴포넌트들이 cssProp 을 전달 받고 적용하도록 수정
Close #492, #493
> [#492, #493] TextEditor 컴포넌트 리팩터링 & 글자 수 증가에 따른 높이조절이 되지 않는 문제 해결

- backend/pick-git/.gitignore
> [#502] 부하 및 스트레스 테스트를 위한 스테이징 프로필 설정

- backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/Portfolio.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
- backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/domain/UserRepositoryTest.java
- User - Portfolio 연관관계 매핑 빠진 부분을 추가했습니다.
<br/>
Close #506
> [#506] User - Portfolio 연관관계 매핑 추가

- frontend/src/App.tsx
- frontend/src/components/@layout/NavigationHeader/NavigationHeader.tsx
- frontend/src/components/@layout/PortfolioHeader/PortfolioHeader.stories.tsx
- frontend/src/components/@layout/PortfolioHeader/PortfolioHeader.style.ts
- frontend/src/components/@layout/PortfolioHeader/PortfolioHeader.tsx
- frontend/src/components/PortfolioProjectSection/PortfolioProjectSection.stories.tsx
- frontend/src/components/PortfolioProjectSection/PortfolioProjectSection.style.ts
- frontend/src/components/PortfolioProjectSection/PortfolioProjectSection.tsx
- frontend/src/components/PortfolioSection/PortfolioSection.stories.tsx
- frontend/src/components/PortfolioSection/PortfolioSection.style.ts
- frontend/src/components/PortfolioSection/PortfolioSection.tsx
- frontend/src/constants/localStorageKey.ts
- frontend/src/constants/messages.ts
- frontend/src/constants/placeholder.ts
- frontend/src/constants/urls.ts
- frontend/src/pages/PortfolioPage/PortfolioPage.style.ts
- frontend/src/pages/PortfolioPage/PortfolioPage.tsx
- frontend/src/services/hooks/@common/useLocalStorage.ts
- frontend/src/services/hooks/useFollow.ts
- frontend/src/services/hooks/usePortfolioIntro.ts
- frontend/src/services/hooks/usePortfolioProject.ts
- frontend/src/services/hooks/usePortfolioProjects.ts
- frontend/src/services/hooks/usePortfolioSection.ts
- frontend/src/services/hooks/usePortfolioSectionItem.ts
- frontend/src/utils/layout.ts
- PortfolioPage 와 그 기능을 구현한다.
Close #494
> [#494] 포트폴리오 기능 구현

- backend/pick-git/src/main/resources/db/migration/V3__add_user_to_portfolio.sql
> [#510] 누락된 칼럼 Flyway에 추가한다.

- frontend/src/components/@shared/GridFeed/GridFeed.tsx
- frontend/src/pages/SearchPage/SearchPage.tsx
- frontend/src/services/hooks/@tests/useSearchUserData.test.tsx
- frontend/src/services/hooks/useSearchPostData.ts
- frontend/src/services/hooks/useSearchUserData.ts
- frontend/src/services/queries/search.ts
- search page에서 탭별 요청 (user 검색, post 검색) 분리
<br/>
Close #516
> [#516] search page 탭별 요청 분리

- backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/application/PortfolioService.java
- 남 포트폴리오 조회 시 발생하는 버그를 해결했습니다.
<br/>
Close #523
> [#523] 포트폴리오 조회 기능 버그 해결

- frontend/src/App.tsx
- frontend/src/components/@layout/PortfolioHeader/PortfolioHeader.tsx
- frontend/src/components/PostSelector/PostSelector.tsx
- frontend/src/pages/PortfolioPage/PortfolioPage.tsx
- 프로젝트 섹션 추가 시 인피니트 스크롤링이 적용되지 않는 문제 해결
- 포트폴리오 기능 API 연동 임시 해제
<br/>
Close #527
> [#527] 프로젝트 섹션 추가 시 인피니트 스크롤링이 적용되지 않는 문제 해결

- backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/application/TagService.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/infrastructure/GithubTagApiRequester.java
- backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/presentation/TagController.java
> [#545] tag 패키지 코드 포맷팅 및 SonarLint 기반 리팩토링 

- README.md
https://github.com/woowacourse-teams/2021-pick-git/tree/docs/readme
여기서 보시면 됩니다.
<br/>
Close #467
> [#467] README 업데이트

- backend/pick-git/.gitignore
- backend/pick-git/build.gradle
- build.gradle에서 JaCoCo 및 SonarQube와 관련한 부분을 모두 삭제했습니다 !
> [저가형 서비스] JaCoCo 및 SonarQube 삭제
