woowacourse-teams/2021-pick-git

frontend/src/App.style.ts
frontend/src/assets/icons/index.tsx
frontend/src/components/@shared/Chip/Chip.tsx
frontend/src/components/@shared/TextEditor/TextEditor.stories.tsx
frontend/src/components/@shared/TextEditor/TextEditor.style.ts
frontend/src/components/@shared/TextEditor/TextEditor.tsx

TextEditor 컴포넌트 구현
- React.CSSProperties, HTMLTextElement 타입을 extends 하지 않음
- width, heigth, fontSize의 타입을 string으로 강제
- HTMLTextElement사용 시 알수 없는 충돌
- autoGrow prop이 true일 경우 작성한 글의 줄 수에 따라 textarea의 height도 늘어남

[#17] TextEditor 컴포넌트 구현

---

frontend/src/assets/icons/go-back.svg
frontend/src/assets/icons/go-forward.svg
frontend/src/components/@layout/SearchHeader/SearchHeader.tsx
frontend/src/components/@layout/StepHeader/StepHeader.tsx
frontend/src/components/@shared/ImageSlider/ImageSlider.stories.tsx
frontend/src/components/@shared/ImageSlider/ImageSlider.style.ts
frontend/src/components/@shared/ImageSlider/ImageSlider.tsx
frontend/src/services/hooks/@common/useThrottle.ts

- 이미지를 순서대로 정렬
- 전체 slider의 height는 가장 height가 큰 이미지를 기준으로한다.
- slider의 height보다 작은 이미지의 상하 공백은 검은 배경으로 채운다.
- 버튼 및 좌우 스크롤을 통해 슬라이드 할 수 있다.
- useTrottle 추가
- goBack, goForward svg가 currentColor를 받도록 수정

[#4] ImageSlider 컴포넌트 구현

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/JwtTokenProvider.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/dto/OAuthProfileResponse.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/JwtTokenProviderImpl.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/OAuthController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/dto/OAuthLoginUrlResponse.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/dto/OAuthTokenResponse.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/IgnoreAuthenticationInterceptor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/profile/BasicProfile.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/profile/GithubProfile.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/OAuthAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/AuthenticationPrincipalArgumentResolverTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/OAuthControllerTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/interceptor/AuthenticationInterceptorTest.java

* 리팩토링 내용
* URL앞에 `/api` 추가
* 로그인 관련 요청 반환값으로 json 형식이 반환되도록 리팩토링
* 테스트 추가
* 슬라이스 테스트
* 통합 테스트
* OAuth Access Token 저장소 테스트
* 인수테스트 완성되는대로 커밋할게유~
* 추가 고려사항
* 예외처리 전략에 따라 커스텀 예외 적용
<br>
* 테스트가 원활하게 돌아가려면 `test` yml 파일을 설정해주어야 합니다! 슬랙에 있는 것을 참고하세유
<br>

[#76] 로그인 기능 리팩토링 및 테스트 추가

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/UserService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/UserProfileServiceDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/follow/Followings.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/UserProfileResponseDto.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/user/application/UserServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/user/application/UserServiceMockTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/user/integration/UserIntegrationTest.java

- 로그인 된 상태에서 본인 프로필 조회 시 `following` 데이터는 `null`로 반환 
- 비로그인 된 상태에서 타인의 프로필 조회 시 `following` 데이터는 `null`로 반환
- 로그인 된 상태에서 팔로우 중인 타인의 프로필 조회 시 `following` 데이터는 `true` 반환
- 로그인 된 상태에서 팔로우 중이 아닌 타인의 프로필 조회시 `following` 데이터는 `false` 반환

[#113] 프로필 조회시 팔로우 여부 기능 구현

---

backend/pick-git/src/test/java/com/woowacourse/pickgit/TestJpaConfiguration.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/post/domain/PostRepositoryTest.java

* @DataJpaTest는 DB 관려 Bean들만 로드하는데, Jpa Auditing을 허용하는 @EnableJpaAuditing 관련 설정을 로드하지 않아 서버 쪽에서는 빌드시 테스트가 실패합니다.
* 로컬에서는 테스트 성공했지만, 실제로 createdAt이라는 LocalDateTime이 null로 들어옴을 확인할 수 있었습니다.
* 이에 TestConfiguration을 추가했습니다.
* SpringBoot 통합 테스트의 경우 @SpringApplication 애너테이션이 달린 클래스를 로드하는데, @EnableJpaAuditing을 해당 메인 클래스에 달아두면 SpringBoot 통합 테스트는 잘 동작하지만, @WebMvcTest는 실패하게 됩니다. @WebMvcTest 슬라이싱 테스트는 @SpringApplication 애너테이션 클래스를 탐색하지 않고 웹 관련 Bean들만 로드하기 때문입니다.
* 다만 제가 @EnableJpaAuditing 애너테이션을 별도로 JpaConfiguration이라고 하는 @Configuration 파일에 분리해서, @WebMvcTest는 여태까지 터지지 않고 Auditing 관련 Bean을 잘 읽어들인것같네요.  (예전에 삽질했었는데... https://xlffm3.github.io/spring%20&%20spring%20boot/JPAError/)
* 추후 jpaAuditing 기능을 사용하고자 하는 모든 슬라이싱 테스트 (통합 테스트는 제외)는 해당 설정 파일을 임포트해야합니다.

[hotfix] Post의 @DataJpaTest 테스트 실패 에러 복구

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/config/PostTestConfiguration.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/PickGitApplicationTests.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/OAuthAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/dao/OAuthAccessTokenDaoTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/post/PostTestConfiguration.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/post/presentation/PostAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/post/presentation/PostControllerTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/tag/presentation/TagAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/user/application/UserServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/user/integration/UserIntegrationTest.java

* s3storage bean 정의된 configuration 파일이 두 개 존재해서 생기는 이슈 및 profile 수정
* 테스트는 잘 돌지만 현재 test profile로 어플리케이션 실행시 빌드가 되지 않음

[hotfix] s3storage bean 탐색을 하지 못하는 버그 수정

---

.gitmodules

master -> main
서브 모듈의 기본 branch는 master로 설정, 하지만 main으로 rename됨에 따라 발생하는 에러를 해결한다.
https://leveloper.tistory.com/176

[#153] 서브모듈 branch 변경

---

backend/pick-git/build.gradle
backend/pick-git/src/main/java/com/woowacourse/pickgit/common/network/RestTemplateClient.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/RestClient.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/S3Storage.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/post/infrastructure/S3StorageTest.java

- s3Proxy로부터 오는 응답 형식의 착오로 인한, 파싱 에러 수정.
- 기존, ["url1", "url2"] 로 반환된다고 생각했으나, 실제로는 {urls:["url1","url2"]} 형식으로 반환.
- RestTemplate 의 ConnectionPool 사용을 위한 추상화
- 기본 RestTemplate는 ConnectionsPool을 사용하지 않는다(스프링에서 기본적으로 SimpleRestTemplate 구현체를 사용하기 때문). 따라서 apache의  HttpClient를 이용하여 커넥션 풀을 이용할 수 있도록 수정

[#152] 응답 파싱 에러 수정

---

s3-proxy/s3-proxy/src/main/java/com/woowacourse/s3proxy/web/infrastructure/FileNameGenerator.java
s3-proxy/s3-proxy/src/main/java/com/woowacourse/s3proxy/web/infrastructure/S3Storage.java
s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/S3ProxyAcceptanceTest.java
s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/common/FileFactory.java
s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/common/fileValidator/ImageFileValidatorTest.java
s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/config/StorageTestConfiguration.java
s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/web/infrastructure/FileNameGeneratorTest.java
s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/web/infrastructure/S3StorageIntegrationTest.java
s3-proxy/s3-proxy/src/test/java/com/woowacourse/s3proxy/web/presentation/PickGitStorageControllerTest.java

#160 를 통해 수정하였으나, 실제 요청 시 본래 파일 이름을 기반으로 url이 생성되는 문제가 존재하였다.
소스를 확인해본 결과, 변경되어야 하는 부분이 여러곳임을 확인했고, 이를 기반으로 다시 코드를 작성하고 테스트를 작성하였다.
기존 테스트에서 거르지 못한 이유는... 변경 전 로직이 _파일 전송 -> 파일 주소 반환 -> 테스트 코드에서도 같은 파일 기반으로 주소 생성 -> 같은지 확인_ 이었는데 주소를 생성하는 프로덕션 코드에 수정이 없었기에 거르지 못했었음..
프로덕션 코드를 모두 수정하고 실패하는 테스트에 대한 수정 완료.

[#169] 파일 주소가 제대로 반환되지 않는 버그 수정

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/dto/TokenDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/AuthorizationExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/AuthenticationPrincipalArgumentResolver.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/OAuthController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/AuthHeader.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/AuthenticationInterceptor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/IgnoreAuthenticationInterceptor.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/OAuthAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/application/OAuthServiceMockTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/AuthenticationPrincipalArgumentResolverTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/OAuthControllerTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/interceptor/AuthenticationInterceptorTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/authentication/presentation/interceptor/IgnoreAuthenticationInterceptorTest.java

- 회원/비회원 모두 처리하는 API에서 토큰을 포함하여 보냈다는 것은 로그인이 된 상태인 것이 더 자연스럽다는 의견에 따라 수정한다.
- 기존 로직: 회원/비회원 모두 처리하는 API (ex. /api/posts)에서 토큰이 잘못된 경우 GuestUser로 처리.
- 수정 로직: 회원/비회원 모두 처리하는 API (ex. /api/posts)에서 토큰이 잘못된 경우 401 예외 발생.

[#161] 회원/비회원 모두 받을 수 있는 API 토큰 검증 로직 수정

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/OAuthService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/application/dto/OAuthProfileResponse.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/AuthorizationExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/GithubOAuthClient.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/presentation/interceptor/IgnoreAuthenticationInterceptor.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/authentication/OAuthAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/authentication/AuthenticationInterceptorIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/authentication/AuthenticationPrincipalArgumentResolverIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/authentication/IgnoreAuthenticationInterceptorIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/authentication/OAuthServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/authentication/application/OAuthServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/authentication/dao/OAuthAccessTokenDaoTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/authentication/presentation/OAuthControllerTest.java

1. Github 로그인 요청을 하면 Github 인증 URL을 반환한다.
2. Github 로그인 인증 후 토큰을 발행하여 반환한다.
**참고** 
- invalid 한 code가 올 수 있으나, 해당 예외 처리는 깃헙에서 하므로 따로 검증하지 않음
1. 처음 생성된 JWT 토큰과 OAuth Access Token을 맵에 성공적으로 저장하고 불러온다.
2. 이미 있는 JWT 토큰에 대해서 새로운 OAuth Access Token을 추가해도 성공적으로 덮어씌워진다.
**고민할 부분**
- JWT 토큰을 덮어 씌우는 경우는? → ***JWT 토큰은 유효한데 github단에서 리프레시 된 경우***
- DAO에 토큰 제거 로직 필요 → ***보류***
1. Github 로그인 URL을 반환한다. → 지나치게 단순해서 필요한 테스트인지 모르겠으나 유지 
2. 회원가입(첫 로그인)시 Github Profile을 가져와서 DB에 insert한다.
3. 로그인(첫 로그인이 아닌경우)시 Github Profile을 가져와서 DB에 저장된 기존 정보를 update한다. → ***update 된 여부를 확인하기는 어렵고 userRepository.save() 를 호출하지 않는 것으로 확인***
4. JWT 토큰을 통해 AccessTokenDB에서 LoginUser에 대한 정보를 가져온다. → Mocking 한 것을 테스트 하는 듯한 느낌이 있지만, 슬라이스 테스트이므로 단순 dto 매핑에 대한 테스트를 한다고 생각함
5. AccessTokenDB에 저장되어 있지 않은 JWT 토큰이라면 예외가 발생한다.
6. 빈 JWT …

[#240] Authentication 관련 테스트 코드 리팩토링

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/CommentResponse.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/comment/Comment.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/comment/CommentContent.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/request/CommentRequest.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/factory/PostFactory.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/comment/CommentTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostControllerTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/domain/UserTest.java

<br>
* `PostService.addComment` 에 `flush` 제거.
* `PostService` `EntityManager` 필드 제거.
* 연간관계 도움 메서드 부분
* 변경 전: `User.addComment`에서 User-Comment, Post-Comment의 관계를 이어줌.
* 변경 후: `User.addComment`에선 User-Comment만, `Post.addComment`에서 Post-Comment를 이어줌.
<br>
* 댓글에 경우 `Post`쪽 테스트 코드를 바탕으로 해야하는데, `Post`관련 테스트 코드를 수정하려니 너무 큰 작업이다.
* 예를들어, `Post` 생성하는 것에 빌더 패턴도 없고, 전체적으로 수정해야 할 사항이 보인다.
* 이 부분은 `Post` 테스트 리팩토링이 머지되고, `Comment` 부분을 수정하여 머지시켜야 좋을 듯 하다.
* `PostService` 통합 테스트에서 `@SpringBootTest` 대신 `@DataJpaTest` 사용하는 것이 더 좋아 보인다.
* `TestEntityManager`를 사용하여 테스트하여야 하는데 못하고 있음.
*  토론하여 Post쪽 테스트 리팩토링이 머지되는대로 수정할 계획.
<br>
<br>
* `Comments`
* 성공 - 100자 이하의 댓글을 생성할 수 있다.
* 실패 - 100자 초과의 댓글을 생성할 수 없다.
* 실패 - 댓글은 null이거나 빈 문자열(공백만 있는 문자열 포함)이면 생성할 수 없다.
* `PostRepository`
* 기타 - Post에 Comment를 추가하면 …

[#246] 댓글 테스트 코드를 리팩토링

---

frontend/src/App.tsx
frontend/src/components/@layout/NavigationHeader/NavigationHeader.style.ts
frontend/src/components/@layout/NavigationHeader/NavigationHeader.tsx
frontend/src/components/@shared/ImageSlider/ImageSlider.tsx
frontend/src/components/Feed/Feed.tsx
frontend/src/components/ProfileFeed/ProfileFeed.tsx
frontend/src/components/ProfileTabContents/ProfileTabContents.tsx
frontend/src/constants/layout.ts
frontend/src/constants/urls.ts
frontend/src/pages/ProfilePage/ProfilePage.tsx
frontend/src/pages/UserFeedPage/UserFeedPage.tsx
frontend/src/services/hooks/useUserFeed.ts
frontend/src/services/queries/posts.ts

- 프로필 하단 피드에서 썸네일을 클릭하면 유저 피드 페이지로 이동하고 해당하는 게시물로 anchor한다.
<br/>
- header에서 height가 큰 요소들의 레이아웃이 깨지는 버그 해결 (로그아웃 버튼 레이아웃)
<br/>
Close #225

[#221, #225] 프로필 피드 클릭시 유저 피드 페이지로 이동

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PickGitStorage.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/S3Storage.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/UserService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/request/ProfileEditRequestDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/response/ProfileEditResponseDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/User.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/request/ProfileEditRequest.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/response/ProfileEditResponse.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/factory/FileFactory.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockPickGitStorage.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/user/UserServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/application/UserServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/presentation/UserControllerTest.java

멀티 파트부분이랑 자바 File 관련된 개념이 익숙하지 않아서 삽질을 좀 많이 했네요ㅠ
늦어서 죄송합니다 :)
<br>
- 프로필 수정 기능을 구현
<br/>
- 현재 S3 Storage와 Github API에 요청하는 부분들에 있어서 중복된 부분들이 많은데요.. 논의 후 패키지를 분리시키던지 해야할 듯 합니다!
- 일단 너잘과 상의 결과 `User`에서만 사용하는 S3관련 인터페이스를 빼진 않기로 했습니다. 그래서 일단 기존의 `Post` 패키지에 있는 것을 가져다가 쓰도록 구현되어있습니다. (추후 리팩토링 필요해보입니다.)
<br/>
Close #267

[#267] 프로필 수정 기능을 구현

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/post/PostFormatException.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/post/PostNotBelongToUserException.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/exception/post/PostNotFoundException.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/request/PostDeleteRequestDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/request/PostUpdateRequestDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/response/PostUpdateResponseDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/PostTag.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/content/Images.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/content/PostContent.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/request/PostUpdateRequest.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/response/PostUpdateResponse.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/application/TagService.java
backend/pick-git/src/main/resources/static/docs/index.html
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/authentication/OAuthServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/content/PostContentTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostControllerTest.java

- 사용자는 게시물을 수정한다.
- 유효하지 않은 내용(null)으로 게시물을 수정할 수 없다. - 400 예외
- 유효하지 않은 내용(500자 초)으로 게시물을 수정할 수 없다. - 400 예외
- 사용자는 게시물을 삭제한다.
<br/>
- 사용자는 게시물의 내용을 수정한다.
- 게스트는 게시물의 내용을 수정할 수 없다.
- 해당하는 사용자의 게시물이 아닌 경우 수정할 수 없다. - 400 예외
- 등록되지 않은 게시물의 내용을 수정할 수 없다. - 500 예외
- 사용자는 게시물을 삭제한다.
- 게스트는 게시물을 삭제할 수 없다. - 401 예외
- 해당하는 사용자의 게시물이 아닌 경우 삭제할 수 없다. - 400 예외
- 등록되지 않은 게시물을 삭제할 수 없다. - 500 예외
<br/>
- 사용자는 게시물의 태그, 내용을 수정한다.
- 사용자는 게시물의 태그를 수정한다.
- 사용자는 게시물의 내용을 수정한다.
- 등록되지 않은 게시물을 수정할 수 없다. - 500 예외
- 사용자는 게시물을 삭제한다.
- 등록되지 않은 게시물은 삭제할 수 없다. - 500 예외
<br/>
- 사용자는 게시물을 수정한다.
- 유효하지 않은 내용(null)의 게시물은 수정할 수 없다. - 400 예외
- 유효하지 않은 내용(500자 초과)의 게시물은 수정할 수 없다. - 400 예외
- 유효하지 않은 토큰으로 게시물을 수정할 수 없다. - 401 예외
- 사용자는 게시물을 삭제한다.
- 유효하지 않은 토큰으로 게시물을 삭제할 수 없다. - 401 예외
<br/>
Close #269

[#269] 게시물 수정 및 삭제 기능 구현

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/response/LikeResponseDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/dto/response/LikeResponse.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostControllerTest.java

- DTO 필드명을 바꿨으나, restDocs 에서 바꾸지 않은 버그를 해결
- `likeCount` -> `likesCount`
- `isLiked` -> `likes`
- 모든 primitive `boolean` -> `Boolean`으로 변경 
<br/>
Close #292

[#292] restDocs 필드명 수정 및 Boolean으로 변경

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/Post.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java

- orphanRemoval = true 옵션을 추가했습니다.
- 사용자는 중복되는 태그로 게시물을 수정할 수 없다 테스트도 추가했습니다.
<br/>
Close #308

[#308] 게시물 수정 버그 해결

---

frontend/src/components/GithubStatistics/GithubStatistics.style.ts
frontend/src/components/GithubStatistics/GithubStatistics.tsx
frontend/src/components/ProfileTabContents/ProfileTabContents.tsx
frontend/src/services/hooks/useGithubStatistics.ts
frontend/src/services/queries/githubStats.ts
frontend/src/services/requests/githubStats.ts

- github statistics가 로그인 시에만 보이도록 수정
- github statistics 훅 분리
<br/>
Close #338

[#338] github statistics가 로그인 시에만 보이도록 수정

---

backend/pick-git/src/docs/asciidoc/comment.adoc
backend/pick-git/src/docs/asciidoc/index.adoc
backend/pick-git/src/docs/asciidoc/post.adoc
backend/pick-git/src/docs/asciidoc/profile.adoc
backend/pick-git/src/docs/asciidoc/search.adoc
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostControllerTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/presentation/UserControllerTest.java

- multipart 전송 시 File을 restDocs에 인자로 기록할 때 깨지는 버그를 해결
- 테스트에는 작성이 되어 있으나 restDocs 스니펫 추가가 누락된 것들을 추가
<br/>
- 프로필 수정 관련 restDocs 테스트 코드가 누락되어 추가 
- 스니펫 이름 통일성 있도록 수정
<br/>
Close #361

[#361] RestDocs에 이미지 파일 깨지는 버그 수정 및 누락 스니펫 추가

---

backend/pick-git/src/docs/asciidoc/profile.adoc
backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/UserService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/request/FollowSearchRequestDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/UserRepository.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/response/UserSearchResponse.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/Acceptance_GetFollowingsAndFollowers.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptance_GetFollowingsAndFollowers.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/user/UserServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/application/UserServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/domain/UserRepositoryTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/presentation/UserControllerTest.java

* 특정 유저의 팔로잉 목록과 팔로워 목록 조회
* 인수 테스트, 통합 테스트, 슬라이싱 테스트 작성
<br/>
* 이번에 구현한 기능들 + 추후 좋아요한 유저 목록 조회 기능들이 유저 검색과 비슷한 양상의 요청 및 응답을 받고 있습니다.
* 실제로 이전에 마크가 구현해둔 메서드를 재활용했는데요. 
* 검색할 때는 자기자신이 포함되는 결과는 제거했는데, 팔로잉이나 팔로워 목록 조회 때는 자기 자신이 포함된 결과는 반환해야해서 완벽하게 재활용하지는 못했습니다.
* 따라서 UserController의 팔로잉/팔로워 목록 조회 메서드를 UserSearchController로 옮기는건 어떻게 생각하시나요?
* 엄밀하게 말하면 검색 기능은 아닌데... 관련 유저들을 검색하는 기능인것같기도하고... 아무튼 UserController에 위치시켰는데 고민되네요.
<br/>
Close #339

[#339] 팔로잉 및 팔로워 목록 조회 기능

---

backend/pick-git/build.gradle

문서 생성 에러를 해결합니다.
그루비 문법의 미성숙함으로 인한 버그로 판단됩니다.
dependsOn 을 하면 무조건 적으로 의존하는 부분을 먼저 실행한다고 생각했는데(실제로 그러기도 하고)
파일 복사 부분의 경우는 그렇지 않나 봅니다. 
생성된 html파일을 자르 파일 안으로 옮기지 못하는 버그가 있었습니다.
추측함에 따르면, 빌드 후에(자르파일 생성 후에) 파일 복사가 이루어지는 것 같은데, 소스상으로는 의존성을 먹여두었기 때문에 먼저 파일이 만들어졌어야 하는데... 이유는 잘 모르겠습니다. 디버거로 타고 들어가 봐도, IDE의 EIP가 읽는 부분과 실제 실행부가 다르다고 느껴집니다.
파일 복사 스크립트를 bootJar쪽으로 옮겨 해결하였습니다.
<br/>
관련된 논의 사항으로, 현재 빌드시 테스트와 레스트 독스를 모두 시행하도록 되어 있는데, 빌드와 레스트 독스 실행 시점을 분리하여 파이프 라인을 조금 더 세밀화 시킬 수 있다고 생각하는데 동의 하시나요?
체크아웃 -> 테스트, 레독생성, 빌드 -> 배포
체크아우 -> 빌드(소스코드의 무결함 확인) -> 테스트 -> 레독생성과 빌드(자르 안에 도큐먼트 주입) -> 배포
<br/>
Close #372

[#372] spring rest docs html 생성 버그 해결

---

backend/pick-git/src/main/resources/logback-spring.xml
backend/pick-git/src/main/resources/logback/db-logger.xml
backend/pick-git/src/main/resources/logback/error-logger.xml
backend/pick-git/src/main/resources/logback/info-logger.xml
backend/pick-git/src/main/resources/logback/test/test-access-logger.xml
backend/pick-git/src/main/resources/logback/test/test-basic-logger.xml
backend/pick-git/src/main/resources/logback/warn-logger.xml
s3-proxy/s3-proxy/src/main/resources/logback-spring.xml
s3-proxy/s3-proxy/src/main/resources/logback/error-logger.xml
s3-proxy/s3-proxy/src/main/resources/logback/info-logger.xml
s3-proxy/s3-proxy/src/main/resources/logback/test/test-access-logger.xml
s3-proxy/s3-proxy/src/main/resources/logback/test/test-basic-logger.xml
s3-proxy/s3-proxy/src/main/resources/logback/warn-logger.xml

* 로그 색상 설정 삭제
* 기존에 logs에 전부 모이던 로그 파일들을 db, access, info, warn, error 디렉토리로 수집되도록 변경
* rolling appender를 통해 날짜 별로도 디렉토리를 세분화할 수 있을 것으로 보이는데, 아직은 불필요하다고 사료되어 구현하지 않았스니다.
<br/>
Close #378

[#378] Logback 설정 리팩토링

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/repository/PickGitStorage.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/S3Storage.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/UserService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/request/ProfileImageEditRequestDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/application/dto/response/ProfileImageEditResponseDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/domain/profile/PickGitProfileStorage.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/S3PickGitProfileStorage.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/UserController.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/request/ProfileDescriptionRequest.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/response/ProfileDescriptionResponse.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/presentation/dto/response/ProfileImageEditResponse.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockPickGitProfileStorage.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockPickGitStorage.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/config/InfrastructureTestConfiguration.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/user/UserServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/application/UserServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/presentation/UserControllerTest.java

- 기존 프로필 수정
- 멀티파트를 이용하여 이미지 + 내용(한 줄 소개)를 한번에 수정. (POST)
- 변경후 프로필 수정 (API 분리)
- Body에 이미지 바이트 배열 보내서 수정. (PUT)
- 내용(한 줄 소개) 수정. (PUT)
<br>
이미지 변경시 아래와 같이 바디에 바이트 배열을 보내서 수정하는 방식입니다.
<br>
- 바이트 배열을 그대로 받는 것이라서 이미지 수정 부분 restdocs를 어떻게 작성해야 할지 모르겠네요... 더 찾아보고 방법이 있으면 적용해보겠습니다!
<br/>
Close #340

[#340] 프로필 이미지 수정/정보 수정 API 기능 분리

---

backend/pick-git/src/docs/asciidoc/post.adoc
backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/dto/request/SearchRepositoryRequestDto.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/util/PlatformRepositorySearchExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/extractor/GithubRepositorySearchExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/requester/GithubRepositoryApiRequester.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/presentation/PostController.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostRepositorySearchAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockRepositoryApiRequester.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/infrastructure/GithubRepositorySearchExtractorTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostControllerTest.java

- Post 업로드 시 사용자의 레포지토리를 검색을 통해 가지고 오는 기능을 구현한다.
- Pagination을 적용한다.
- 사용자의 Keyword를 통해서 Github API 에 해당 단어를 포함하는 레포지토리를 모두 조회하여 반환한다.
- 예외 케이스
1. Github에 보내어지는 Access Token이 invalid 할 경우 예외 방생
2. Github에 존재하지 않는 username 계정의 repo 검색 시 예외 발생
<br/>
현재 이전에 말했듯이 `PlatformApiRequester`를 공유하고 있는데, 그래서 테스트에서도 `MockRepositoryApiRequest`를 의존하고 있어요! 그런데 현재 `MockRepositoryApiRequest`가 굉장히 특정 유저의 Repository를 조회하는 쪽으로 구현이 되어 있어서 거기에 Github repo를 검색하는 로직을 끼워넣으려다 보니까 코드가 상당히 지저분해 진 것 같아요.
따로 `MockRepositoryApiRequest`를 작성하려다보니 프로덕션 코드에는 두 requester가 분리되어 있지 않아서 자동으로 주입을 해줄 수 가 없는 상황입니다. 아마 `MockRepositoryApiRequest` 코드를 개선하는 방법을 찾아야 하는 것 같은데 이전 레포지토리 조회 코드와 깊게 연관이 되어 있어서 우선은 그냥 올립니다!  
<br/>
Close #359

[#359] Github Repositories 검색 기능 구현

---

frontend/src/components/RepositorySelector/RepositorySelector.tsx
frontend/src/constants/urls.ts

- 검색어가 없을 때는 기본 레포 목록 가져오기 api 를, 검색어가 있을 때는 레포 목록 검색 api를 사용하도록 변경
<br/>
Close#427

[#427] 레포 목록 검색 api 주소 수정

---

backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/user/UserAcceptance_GetFollowingsAndFollowers.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/mockapi/MockGithubOAuthClient.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/request_builder/LoginBuilder.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/comment/CommentServiceIntegrationTest_queryComments.java

로그인 요청 시 전송하는 code에 이름을 담아 보내면, 이름을 기반으로 Token을 전송하도록 변경하였습니다.
PickgitRequest 를 사용하면, `withUser({userName})` 을 통해서 특정 유저의 토큰으로 로그인 요청을 보낼 수 있습니다.
파라메터 없는 `withUser()` 는 랜덤 유저로 전송하도록 변경하였습니다.
이런식으로 전송하면 testUser라는 유저의 토큰으로 전송됨.
<br/>
<br/>
Close #438

[#438] 테스트에서 유저 이름을 기반으로 토큰을 생성하도록 변경

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostDtoAssembler.java

현재는 단순 limit으로 제한하였으나, 추후 설계 변경이 일어날 경우 전체 코드가 변경되기에  기능 구현에만 초점을 두겠습니다.
<br/>
<br/>
Close #444

[#444] 피드 조회시 함께 오는 댓글의 갯수를 3개로 제한

---

frontend/src/App.tsx
frontend/src/components/Feed/Feed.tsx
frontend/src/components/UserList/UserList.tsx
frontend/src/constants/messages.ts
frontend/src/constants/urls.ts
frontend/src/pages/PostLikePeoplePage/PostLikePeoplePage.tsx
frontend/src/services/hooks/usePostLikePeople.ts
frontend/src/services/queries/postLikePeople.ts
frontend/src/services/requests/postLikePeople.ts

- 좋아요가 0 명일 경우 이용자에게 피드백 해주고 페이지 이동이 일어나지 않도록 변경
Close #449

[#449] 게시글 좋아요 이용자 목록 페이지 이동 라우팅이 되지 않는 문제 해결

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/config/OAuthConfiguration.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/config/auth_interceptor_register/scanner/package_scanner/PackageScanner.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/config/auth_interceptor_register/scanner/package_scanner/SourceVisitor.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/config/auth_interceptor_register/scanner/PackageScannerTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/config/auth_interceptor_register/scanner/SourceVisitorTest.java

파일 탐색 위치가, ClassLoader 기준이 아닌, jar기준으로 되어있어 발생한 버그.
<br/>
<br/>
Close #451

[#451] classname 파싱 버그를 해결한다.

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostDtoAssembler.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/application/PostFeedService.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/domain/repository/PostRepository.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/acceptance/post/PostAcceptanceTest_searchPost.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/common/factory/PostFactory.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostFeedServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/post/PostFeedServiceIntegrationTest_search.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostFeedServiceTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/application/PostFeedService_search.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/domain/PostRepositoryTest_search.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostFeedControllerTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostFeedControllerTest_searchPosts.java

* 비로그인일때는 기존처럼 전체 게시물을 최신순으로 페이징
* 로그인일때는 내가 팔로잉한사람들(나포함)의 게시물을 최신순으로 페이징
* 관련 슬라이싱 + 통합 테스트 작성
<br/>
* 현재 인수테스트를 작성하지 못했습니다. 정확히는 홈피드에 대한 인수 테스트는 있는데, 여러 사람의 글을 조회하는 테스트 환경을 가진 테스트가 아닙니다. 이를 개선하려고 하는데요.
* 예전에 마크가 만들어둔 방법으로는 여러 명의 테스트 유저를 등록해두고 토큰을 가지고 환경을 조성할 수 있을 것 같습니다.
```java
//마크 방식
private ExtractableResponse<Response> 로그인_요청(User user) {
// given
String oauthCode = "1234";
String accessToken = "oauth.access.token";
OAuthProfileResponse oAuthProfileResponse = new OAuthProfileResponse(
user.getName(), user.getImage(), user.getDescription(), user.getGithubUrl(),
user.getCompany(), user.getLocation(), user.getWebsite(), user.getTwitter()
);
// mock
when(oAuthClient.getAccessToken(oauthCode)).thenReturn(accessToken);
when(oAuthClient.getGithubProfile(accessToken)).thenReturn(oAuthProfil …
```

[#355] 홈 피드를 새로운 기준으로 정렬

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/repository/PortfolioRepository.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/presentation/PortfolioController.java

- JPQL 문법을 수정했습니다.
```java
// 전
@Query("select Portfolio from Portfolio p where p.user.basicProfile.name = :username")
Optional<Portfolio> findPortfolioByUsername(@Param("username") String username);
// 후
@Query("select p from Portfolio p where p.user.basicProfile.name = :username")
Optional<Portfolio> findPortfolioByUsername(@Param("username") String username);
```
- API URI를 수정했습니다.
```java
// 전
@RestController
@RequestMapping("/api/portfolio")
@CrossOrigin(value = "*")
public class PortfolioController {
// 후
@RestController
@RequestMapping("/api/portfolios")
@CrossOrigin(value = "*")
public class PortfolioController {
```
<br/>
Close #521

[#521] 포트폴리오 기능 버그 해결

---

backend/pick-git/build.gradle
backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/GithubOAuthClient.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/extractor/GithubRepositoryExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/post/infrastructure/extractor/GithubRepositorySearchExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/tag/infrastructure/GithubTagExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/calculator/GithubContributionCalculator.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/extractor/GithubContributionExtractor.java
backend/pick-git/src/main/java/com/woowacourse/pickgit/user/infrastructure/requester/GithubFollowingRequester.java
backend/pick-git/src/main/resources/application.yml
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/tag/TagServiceIntegrationTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/infrastructure/GithubRepositoryExtractorTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/infrastructure/GithubRepositorySearchExtractorTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/post/presentation/PostFeedControllerTest_searchPosts.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/tag/infrastructure/GithubTagExtractorTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/infrastructure/GithubContributionCalculatorTest.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/unit/user/infrastructure/GithubContributionExtractorTest.java

* 현재 깃헙으로 api 요청을 보내는 url이 클래스 내부 상수로 관리되고 있습니다.
* 성능 테스트를 하는 경우, 이러한 외부 연동 모듈 서비스는 인터페이스로 mocking하지 않고 별도의 외부 mock 서버를 띄우는 것을 권장하고 있습니다.
* 이를 위해 staging profile에서 url을 바꿔칠 수 있도록 관련 api url을 상수로 관리합니다.
* oauth 관련 상수는 security에 정의합니다.
<br/>
<br/>
Close #529

[#529] API URL을 Property 상수로 관리

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/portfolio/domain/Portfolio.java

사용자의 GitHub discription이 없을 경우 프로트폴리오 생성 시 한줄 소개란이 null로 들어가면서 null point exception이 발생합니다.
<br/>
<br/>
Close #763

[#763] portfolio가 생성이 안되는 버그를 해결.

---

frontend/src/components/Feed/Feed.tsx
frontend/src/hooks/common/useStep.ts
frontend/src/hooks/service/useFeedMutation.ts
frontend/src/pages/HomeFeedPage/HomeFeedPage.tsx
frontend/src/pages/PortfolioPage/PortfolioPage.tsx
frontend/src/services/queries/portfolio.ts
frontend/src/services/queries/profile.ts

- 검색 결과로 보이는 게시글들에서 좋아요가 수행되지 않는 문제를 해결
- 비동기 데이터의 cacheTime 을 설정
- 프로필 데이터 4시간으로 설정
- 포트폴리오 데이터 0초로 설정
- 이용자가 포트폴리오를 초기화하지 않았으면 이에 맞는 에러 화면을 보여준다.
- 포트폴리오가 초기화 되지 않은 경우에 대해 잘못된 에러 페이지가 보이는 문제 해결
- 필요 없는 profile 데이터 요청 삭제
- 앞으로 가기와 슬라이더가 연동되지 않는 문제 해결
<br/>
Close #767, #768, #769

[#767, #768, #769] 운영서버 배포 중 발견된 버그 해결

---

backend/pick-git/src/main/java/com/woowacourse/pickgit/authentication/infrastructure/dao/RedisOAuthAccessTokenDao.java
backend/pick-git/src/test/java/com/woowacourse/pickgit/integration/authentication/OAuthServiceIntegrationTest.java

- 토큰 만료기간이 지나면 Redis에서 해당 토큰이 자동으로 삭제되도록 리팩토링
<br/>
Close #765

[#765] Redis Token 저장시 TTL 설정되도록 리팩토링
